apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-first-app
  namespace: argocd
  labels:
    app: my-first-app
spec:
  project: default
  source:
    repoURL: https://github.com/tiagoReichert/backstage-components
    targetRevision: HEAD
    path: my-first-app/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: my-first-app
