apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-first-app
  description: My first Backstage-deployed app
  annotations:
    backstage.io/kubernetes-id: my-first-app
    backstage.io/kubernetes-namespace: my-first-app
    github.com/project-slug: tiagoReichert/backstage-components
spec:
  type: website
  lifecycle: experimental
  owner: user:guest
