apiVersion: v1
kind: Service
metadata:
  name: my-first-app
  namespace: my-first-app
  labels:
    app: my-first-app
    backstage.io/kubernetes-id: my-first-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: my-first-app
